import io
import os
import sys
import unittest
from unittest.mock import MagicMock, patch

# Add project root and empire scripts to path
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
sys.path.append(PROJECT_ROOT)
sys.path.append(os.path.join(PROJECT_ROOT, "src", "core"))

from src.core.sv_engine import SovereignEngine
from factories import create_scenario, create_vector_engine, create_warlord
from src.core.ui import HUD


# [Ω] GENERATED BY EMPIRE COMPILER
class TestEngine_contracts(unittest.TestCase):
    def setUp(self):
        self.captured_output = io.StringIO()
        sys.stdout = self.captured_output
        # GIVEN: State Injection
        # Engine is initialized [HSV]
        self.engine = create_vector_engine()
        # Engine is initialized [HSV]
        self.engine = create_vector_engine()
        # Engine is initialized [HSV]
        self.engine = create_vector_engine()

    def tearDown(self):
        sys.stdout = sys.__stdout__

    @patch('src.core.sv_engine.SovereignEngine._init_vector_engine')
    @patch('src.core.utils.input_with_timeout')
    @patch('src.core.utils.load_config')
    @patch('subprocess.run')
    @patch('src.core.ui.HUD._speak')
    def test_transition(self, mock_speak, mock_subprocess, mock_config, mock_input, mock_init_vector):
        # Setup Mocks
        mock_config.return_value = {"persona": "ALFRED"} # Force Cyan Theme
        mock_speak.return_value = "Install skill?" # Force deterministic dialogue
        mock_vector = MagicMock()
        mock_init_vector.return_value = mock_vector
        mock_subprocess.return_value.returncode = 0
        mock_input.return_value = 'y'

        # >>> EXECUTING CONTRACT 1: STATUS CHECK <<<
        # GIVEN Engine is initialized [HSV]
        engine = SovereignEngine()
        
        # WHEN Query "status" is executed
        # Mock search result for "status"
        mock_vector.search.return_value = [{'trigger': 'STATUS', 'score': 1.0, 'is_global': False}]
        engine.run("status")
        
        # THEN HUD Output contains "STATUS" [HUD]
        output = self.captured_output.getvalue()
        self.assertIn("STATUS", output) 
        self.assertIn("\033[36m", output) # ANSI Cyan Check
        
        # THEN Output contains "SovereignVector" (It might not if we mocked it, but let's check HUD structure)
        # The HUD renders "Match: STATUS"
        self.assertIn("Match", output)

        # Clear output for next scenario
        self.captured_output.truncate(0)
        self.captured_output.seek(0)
        
        # >>> EXECUTING CONTRACT 2: PROACTIVE INSTALL <<<
        # WHEN Query "GLOBAL:git-assistant" is executed
        mock_vector.search.return_value = [{'trigger': 'GLOBAL:git-assistant', 'score': 0.95, 'is_global': True}]
        engine.run("GLOBAL:git-assistant")
        
        # THEN Proactive Install triggers for "git-assistant" [HUD]
        output = self.captured_output.getvalue()
        self.assertIn("PROACTIVE INSTALL", output)
        self.assertIn("\033[36m", output)
        
        # THEN Output contains proactive install prompt [HUD]
        # Since input_with_timeout is mocked, we verify the prompt it was called with
        # [ALFRED] The butler speaks with his own voice — prompt text varies by persona dialogue.
        mock_input.assert_called()
        args, _ = mock_input.call_args
        self.assertIn("[Y/n]", args[0])
        
        # Clear output
        self.captured_output.truncate(0)
        self.captured_output.seek(0)

        # >>> EXECUTING CONTRACT 3: SINK <<<
        # WHEN Query "coffee" is executed (Intent Sink)
        mock_vector.search.return_value = [] # No match
        engine.run("coffee")
        
        # THEN Output matches "NO DATA FOUND" or Sink Response [HUD]
        output = self.captured_output.getvalue()
        # The HUD renders "Match: NONE" in Red
        self.assertIn("NONE", output)
        self.assertIn("\033[31m", output) # Red

if __name__ == '__main__':
    unittest.main()