Feature: TALIESIN - Textual Articulation and Lore Ingestion Engine for Social Interface Narratives
  As the Warlord of Corvus Star
  I want an autonomous spoke to generate social media content in my style
  So that the project's lore and technical progress are chronicled on X.

  Background:
    Given the TALIESIN spoke is registered in the Gungnir Control Plane
    And the Lore Corpus exists in ".lore/"
    And the X API credentials are configured in ".env.local"

  Scenario: Style Ingestion & Analysis
    Given no style template exists for the current session
    And raw writing samples are present in ".lore/"
    When I run "cstar lore --ingest"
    Then TALIESIN should analyze the corpus and generate a temporary "style template"
    And the template should capture cadence, vocabulary, and formatting quirks.

  Scenario: Generating Technical Articles (Article Mode)
    Given the system has new entries in the dev journal and memory
    And the "Article Mode" flag is set
    When I run "cstar lore --mode article"
    Then TALIESIN should pull data from "dev_journal.qmd" and "memory.qmd"
    And generate a logically structured draft with technical takeaways.

  Scenario: Generating Narrative Lore (Story Mode)
    Given the system has developmental memories
    And the "Story Mode" flag is set
    When I run "cstar lore --mode story"
    Then TALIESIN should pull abstract context from "memory.qmd"
    And rotate the data into a narrative arc emphasizing project lore.

  Scenario: The Staging Gate & Feedback Loop
    Given a draft has been generated by TALIESIN
    When the system holds the post for review
    And I provide a "terminal prompt interaction" response
    Then the draft should be either:
      | Action   | Result                                      |
      | Approved | Pushed to the X API                         |
      | Edited   | Saved back to ".lore/" for reinforcement    |
      | Rejected | Discarded without posting                   |
