import { z } from 'zod';
import {
    WORKER_ARTIFACT_KINDS,
    WORKER_JOB_PROGRESS_PHASES,
    WORKER_JOB_STATES,
    WORKER_KINDS,
} from '../../../types/worker_job.js';

const safeLogicalRef = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const safeArtifactName = /^[A-Za-z0-9][A-Za-z0-9._ -]{0,127}$/;
const safeIdentifier = /^[A-Za-z0-9][A-Za-z0-9._:-]{7,159}$/;

export const workerArtifactExpectationSchema = z.object({
    name: z.string()
        .regex(safeArtifactName)
        .describe('Logical artifact name; never a filesystem path.'),
    artifact_kind: z.enum(WORKER_ARTIFACT_KINDS)
        .describe('Expected artifact category.'),
    required: z.boolean().optional().default(true)
        .describe('Whether the worker must produce this artifact before success.'),
}).strict();

const workerArtifactExpectationsSchema = z.array(workerArtifactExpectationSchema)
    .min(1)
    .max(20)
    .superRefine((artifacts, context) => {
        const seen = new Set<string>();
        artifacts.forEach((artifact, index) => {
            const key = `${artifact.artifact_kind}\0${artifact.name.trim()}`;
            if (seen.has(key)) {
                context.addIssue({
                    code: 'custom',
                    path: [index],
                    message: 'Expected artifact names and kinds must be unique.',
                });
            }
            seen.add(key);
        });
    });

export const publicWorkerArtifactSchema = z.object({
    artifact_id: z.string(),
    artifact_kind: z.enum(WORKER_ARTIFACT_KINDS),
    name: z.string(),
    media_type: z.string(),
    byte_count: z.number().int().nonnegative(),
    sha256: z.string().regex(/^[a-f0-9]{64}$/i),
    created_at: z.number().int().nonnegative(),
}).strict();

export const publicWorkerJobSchema = z.object({
    job_id: z.string(),
    bead_id: z.string().optional(),
    worker_kind: z.enum(WORKER_KINDS),
    objective: z.string(),
    workspace_ref: z.string(),
    expected_artifacts: z.array(workerArtifactExpectationSchema),
    state: z.enum(WORKER_JOB_STATES),
    progress: z.object({
        percent: z.number().int().min(0).max(100),
        phase: z.enum(WORKER_JOB_PROGRESS_PHASES),
    }).strict(),
    cancel_requested: z.boolean(),
    failure: z.object({
        code: z.string(),
        summary: z.string().optional(),
    }).strict().optional(),
    attempt_count: z.number().int().nonnegative(),
    version: z.number().int().positive(),
    artifacts: z.array(publicWorkerArtifactSchema),
    created_at: z.number().int().nonnegative(),
    updated_at: z.number().int().nonnegative(),
    started_at: z.number().int().nonnegative().optional(),
    terminal_at: z.number().int().nonnegative().optional(),
}).strict();

export const startWorkerJobInputSchema = z.object({
    worker_kind: z.enum(WORKER_KINDS)
        .describe('Protected worker role. CStar resolves its private Hermes profile.'),
    objective: z.string().trim().min(1).max(8_000)
        .describe('Natural-language work objective.'),
    workspace_ref: z.string()
        .regex(safeLogicalRef)
        .refine((value) => !value.includes('..'), 'workspace_ref cannot contain path traversal.')
        .describe('Logical workspace identifier, never a host path.'),
    expected_artifacts: workerArtifactExpectationsSchema
        .describe('Bounded artifact contract for the worker result.'),
    idempotency_key: z.string().regex(safeIdentifier)
        .describe('Stable retry key generated by the caller; do not ask the user for it.'),
    bead_id: z.string().trim().min(1).max(160).optional()
        .describe('Optional existing Hall bead to associate with the job.'),
}).strict();

export const getWorkerJobInputSchema = z.object({
    job_id: z.string().trim().min(1).max(160),
}).strict();

export const cancelWorkerJobInputSchema = z.object({
    job_id: z.string().trim().min(1).max(160),
    reason: z.string().trim().min(1).max(500).optional(),
    expected_version: z.number().int().positive().optional()
        .describe('Optional optimistic concurrency version from a prior read.'),
}).strict();

export const fetchWorkerArtifactInputSchema = z.object({
    job_id: z.string().trim().min(1).max(160),
    artifact_id: z.string().trim().min(1).max(160),
}).strict();

export const startWorkerJobOutputSchema = z.object({
    status: z.enum(['queued', 'existing']),
    deduplicated: z.boolean(),
    execution_available: z.literal(false),
    job: publicWorkerJobSchema,
}).strict();

export const getWorkerJobOutputSchema = z.object({
    status: z.literal('ok'),
    execution_available: z.literal(false),
    job: publicWorkerJobSchema,
}).strict();

export const cancelWorkerJobOutputSchema = z.object({
    status: z.enum(['cancelled', 'cancel_requested']),
    changed: z.boolean(),
    job: publicWorkerJobSchema,
}).strict();

export const fetchWorkerArtifactOutputSchema = z.object({
    status: z.literal('ok'),
    artifact: publicWorkerArtifactSchema,
    delivery: z.object({
        mode: z.literal('inline_text'),
        text: z.string(),
    }).strict(),
}).strict();

export type StartWorkerJobArgs = z.infer<typeof startWorkerJobInputSchema>;
export type GetWorkerJobArgs = z.infer<typeof getWorkerJobInputSchema>;
export type CancelWorkerJobArgs = z.infer<typeof cancelWorkerJobInputSchema>;
export type FetchWorkerArtifactArgs = z.infer<typeof fetchWorkerArtifactInputSchema>;

export function isWorkerJobsV2Enabled(
    env: NodeJS.ProcessEnv = process.env,
): boolean {
    return env.CSTAR_KERNEL_ENABLE_WORKER_JOBS_V2 === '1';
}
