import os
import re
import json
from typing import Dict, List, Any

class EmpireCompiler:
    """
    [Ω] THE COMPILER OF RUNES
    Converts .qmd contracts into executable Internal Representation (IR).
    """

    def __init__(self, legend_path: str = None):
        self.legend_path = legend_path
        self.patterns = {
            "GIVEN": re.compile(r"GIVEN\s+(.*)", re.IGNORECASE),
            "WHEN": re.compile(r"WHEN\s+(.*)", re.IGNORECASE),
            "THEN": re.compile(r"THEN\s+(.*)", re.IGNORECASE)
        }

    def compile(self, qmd_path: str) -> Dict[str, Any]:
        """Parse a .qmd file and extract the tripartite state cycle."""
        if not os.path.exists(qmd_path):
            raise FileNotFoundError(f"Runes missing at {qmd_path}")

        with open(qmd_path, "r", encoding="utf-8") as f:
            content = f.read()

        ir = {
            "source": qmd_path,
            "given": [],
            "when": [],
            "then": []
        }

        lines = content.splitlines()
        for line in lines:
            line = line.strip()
            for key, pattern in self.patterns.items():
                match = pattern.match(line)
                if match:
                    ir[key.lower()].append(match.group(1).strip())

        return ir

    def generate_boilerplate(self, ir: Dict[str, Any], output_path: str):
        """Generate the Python verification script (Linscott Standard)."""
        # [ALFRED's Observation]: "The Master requires deterministic output."
        # [ODIN's Void]: "FORGE THE TEST!"
        
        test_name = os.path.basename(ir['source']).replace(".qmd", "")
        
        code = [
            'import unittest',
            'import sys',
            'import os',
            '',
            '# [Ω] GENERATED BY EMPIRE COMPILER',
            f'class Test{test_name.capitalize()}(unittest.TestCase):',
            '    def setUp(self):',
            '        # GIVEN: State Injection'
        ]
        
        for g in ir['given']:
            code.append(f'        # {g}')
            code.append('        pass # TODO: Map to state injection')
            
        code.append('')
        code.append('    def test_transition(self):')
        code.append('        # WHEN: Atomic Transition')
        for w in ir['when']:
            code.append(f'        # {w}')
            code.append('        pass # TODO: Map to driver call')
            
        code.append('')
        code.append('        # THEN: State Projection')
        for t in ir['then']:
            code.append(f'        # {t}')
            code.append('        pass # TODO: Map to semantic assertion')

        code.append('')
        code.append("if __name__ == '__main__':")
        code.append("    unittest.main()")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(code))
        
        # [Ω] SENTINEL AUDIT
        try:
            sentinel_script = os.path.join(os.path.dirname(os.path.dirname(__file__)), "code_sentinel.py")
            if os.path.exists(sentinel_script):
                import subprocess
                subprocess.run([sys.executable, sentinel_script, output_path], capture_output=True)
        except Exception:
            pass # Non-blocking audit

        return output_path

if __name__ == "__main__":
    # Self-test if run directly
    compiler = EmpireCompiler()
    # Mock run
    print("[Ω] COMPILER INITIALIZED")
