import os
import sys
import re
from typing import Any


class EmpireCompiler:
    """
    [Ω] THE COMPILER OF RUNES
    Converts .qmd contracts into executable Internal Representation (IR).
    """

    def __init__(self, legend_path: str | None = None):
        self.legend_path = legend_path
        self.patterns = {
            "GIVEN": re.compile(r"GIVEN\s+(.*)", re.IGNORECASE),
            "WHEN": re.compile(r"WHEN\s+(.*)", re.IGNORECASE),
            "THEN": re.compile(r"THEN\s+(.*)", re.IGNORECASE)
        }

    def compile(self, qmd_path: str) -> dict[str, Any]:
        """Parse a .qmd file and extract the tripartite state cycle."""
        if not os.path.exists(qmd_path):
            raise FileNotFoundError(f"Runes missing at {qmd_path}")

        with open(qmd_path, encoding="utf-8") as f:
            content = f.read()

        ir = {
            "source": qmd_path,
            "given": [],
            "when": [],
            "then": []
        }

        lines = content.splitlines()
        for line in lines:
            line = line.strip()
            for key, pattern in self.patterns.items():
                match = pattern.match(line)
                if match:
                    ir[key.lower()].append(match.group(1).strip())

        return ir

    def generate_boilerplate(self, ir: dict[str, Any], output_path: str):
        """Generate the Python verification script (Linscott Standard)."""
        # [ALFRED's Observation]: "The Master requires deterministic output."
        # [ODIN's Void]: "FORGE THE TEST!"

        test_name = os.path.basename(ir['source']).replace(".qmd", "")

        code = [
            'import unittest',
            'import sys',
            'import os',
            'from unittest.mock import patch, MagicMock',
            'import io',
            '',
            '# Add project root and empire scripts to path',
            'PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))',
            'sys.path.append(PROJECT_ROOT)',
            'sys.path.append(os.path.join(PROJECT_ROOT, ".agent", "scripts"))',
            'sys.path.append(os.path.join(PROJECT_ROOT, ".agent", "scripts", "empire"))',
            '',
            'from factories import create_warlord, create_scenario, create_vector_engine',
            'from ui import HUD',
            '',
            '# [Ω] GENERATED BY EMPIRE COMPILER',
            f'class Test{test_name.capitalize()}(unittest.TestCase):',
            '    def setUp(self):',
            '        self.captured_output = io.StringIO()',
            '        sys.stdout = self.captured_output',
            '        # GIVEN: State Injection'
        ]

        # [Ω] State Injection Logic
        for g in ir['given']:
            code.append(f'        # {g}')
            if "[@]" in g:
                 code.append('        self.state = create_warlord("MAX_LEVEL_TYRANT")')
            elif "[HSV]" in g:
                 code.append('        self.engine = create_vector_engine()')
            else:
                 code.append('        pass')

        code.append('')
        code.append('    def tearDown(self):')
        code.append('        sys.stdout = sys.__stdout__')
        code.append('')

        code.append('    def test_transition(self):')
        code.append('        # WHEN: Atomic Transition')
        for w in ir['when']:
            code.append(f'        # {w}')
            if "[Git]" in w:
                code.append('        with patch("subprocess.run") as mock_run:')
                code.append('            mock_run.return_value.returncode = 0')
                code.append('            # TODO: Call actual function here')
            else:
                code.append('        pass # TODO: Map to driver call')

        code.append('')
        code.append('        # THEN: State Projection')
        for t in ir['then']:
            code.append(f'        # {t}')
            if "[HUD]" in t:
                code.append('        output = self.captured_output.getvalue()')
                code.append('        self.assertIn("\\033[36m", output) # ANSI Cyan Check')
            else:
                code.append('        pass # TODO: Map to semantic assertion')

        code.append('')
        code.append("if __name__ == '__main__':")
        code.append("    unittest.main()")

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(code))

        # [Ω] SENTINEL AUDIT
        try:
            sentinel_script = os.path.join(os.path.dirname(os.path.dirname(__file__)), "code_sentinel.py")
            if os.path.exists(sentinel_script):
                import subprocess
                subprocess.run([sys.executable, sentinel_script, output_path], capture_output=True)
        except Exception:
            pass # Non-blocking audit

        return output_path

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Empire TDD Compiler")
    parser.add_argument("files", nargs="+", help="Path to .qmd contract files")
    args = parser.parse_args()

    compiler = EmpireCompiler()
    for qmd_file in args.files:
        try:
            ir = compiler.compile(qmd_file)
            out_file = qmd_file.replace(".qmd", ".py")
            # Prefix with test_ if not present
            dirname, basename = os.path.split(out_file)
            if not basename.startswith("test_"):
                basename = "test_" + basename
            out_file = os.path.join(dirname, basename)

            final_path = compiler.generate_boilerplate(ir, out_file)
            print(f"[Ω] COMPILED: {qmd_file} -> {final_path}")
        except Exception as e:
            print(f"[!] FAILED: {qmd_file} - {e}")
