import unittest
import sys
import os

# [Ω] GENERATED BY EMPIRE COMPILER
class TestContract_example(unittest.TestCase):
    def setUp(self):
        # GIVEN: State Injection
        # User is Premium [$]
        pass # TODO: Map to state injection

    def test_transition(self):
        # WHEN: Atomic Transition
        # User clicks "Export PDF"
        pass # TODO: Map to driver call

        # THEN: State Projection
        # download starts
        pass # TODO: Map to semantic assertion

if __name__ == '__main__':
    unittest.main()