export const NATIVE_TASK_CONTROL_ERROR_CODES = {
    INVALID_JSON: 'CSTAR_NATIVE_TASK_INVALID_JSON',
    DUPLICATE_FIELD: 'CSTAR_NATIVE_TASK_DUPLICATE_FIELD',
    UNKNOWN_FIELD: 'CSTAR_NATIVE_TASK_UNKNOWN_FIELD',
    NON_CANONICAL: 'CSTAR_NATIVE_TASK_NON_CANONICAL',
    POLICY_INVALID: 'CSTAR_NATIVE_TASK_POLICY_INVALID',
    POLICY_WIDENING: 'CSTAR_NATIVE_TASK_POLICY_WIDENING',
    POLICY_DEPTH: 'CSTAR_NATIVE_TASK_POLICY_DEPTH',
    GENERATION_LOOP: 'CSTAR_NATIVE_TASK_GENERATION_LOOP',
    STALE_CONTROLLER: 'CSTAR_NATIVE_TASK_STALE_CONTROLLER',
    SCOPE_VIOLATION: 'CSTAR_NATIVE_TASK_SCOPE_VIOLATION',
    REPLAY_CONFLICT: 'CSTAR_NATIVE_TASK_REPLAY_CONFLICT',
    PROTECTED_EFFECT: 'CSTAR_NATIVE_TASK_PROTECTED_EFFECT',
    SELECTOR_MISMATCH: 'CSTAR_NATIVE_TASK_SELECTOR_MISMATCH',
    GOAL_MISMATCH: 'CSTAR_NATIVE_TASK_GOAL_MISMATCH',
    COMPETING_LEASE: 'CSTAR_NATIVE_TASK_COMPETING_LEASE',
    CANCEL_ACK_MISSING: 'CSTAR_NATIVE_TASK_CANCEL_ACK_MISSING',
    CANCEL_DUPLICATE: 'CSTAR_NATIVE_TASK_CANCEL_DUPLICATE',
    TERMINAL_BARRIER: 'CSTAR_NATIVE_TASK_TERMINAL_BARRIER',
    TERMINAL_REPLAY_CONFLICT: 'CSTAR_NATIVE_TASK_TERMINAL_REPLAY_CONFLICT',
    SUCCESSION_OVERLAP: 'CSTAR_NATIVE_TASK_SUCCESSION_OVERLAP',
    SUCCESSION_AMBIGUOUS: 'CSTAR_NATIVE_TASK_SUCCESSION_AMBIGUOUS',
    WAIT_DUPLICATE: 'CSTAR_NATIVE_TASK_WAIT_DUPLICATE',
    LATE_EVENT: 'CSTAR_NATIVE_TASK_LATE_EVENT',
    UNDECLARED_ROLE: 'CSTAR_NATIVE_TASK_UNDECLARED_ROLE',
    REPLACEMENT_EXHAUSTED: 'CSTAR_NATIVE_TASK_REPLACEMENT_EXHAUSTED',
    PROTOTYPE_KEY: 'CSTAR_NATIVE_TASK_PROTOTYPE_KEY',
    SURFACE_UNAVAILABLE: 'CORVUS_NATIVE_TASK_SURFACE_UNAVAILABLE',
    FORGE_DEFUNCT: 'CSTAR_FORGE_DEFUNCT',
} as const;

export const NATIVE_TASK_CONTROL_STABLE_ERROR_CODES = Object.freeze({
    GENERATION_LOOP: NATIVE_TASK_CONTROL_ERROR_CODES.GENERATION_LOOP,
    STALE_CONTROLLER: NATIVE_TASK_CONTROL_ERROR_CODES.STALE_CONTROLLER,
    SCOPE_VIOLATION: NATIVE_TASK_CONTROL_ERROR_CODES.SCOPE_VIOLATION,
    REPLAY_CONFLICT: NATIVE_TASK_CONTROL_ERROR_CODES.REPLAY_CONFLICT,
    PROTECTED_EFFECT: NATIVE_TASK_CONTROL_ERROR_CODES.PROTECTED_EFFECT,
    SELECTOR_MISMATCH: NATIVE_TASK_CONTROL_ERROR_CODES.SELECTOR_MISMATCH,
    GOAL_MISMATCH: NATIVE_TASK_CONTROL_ERROR_CODES.GOAL_MISMATCH,
    COMPETING_LEASE: NATIVE_TASK_CONTROL_ERROR_CODES.COMPETING_LEASE,
    CANCEL_ACK_MISSING: NATIVE_TASK_CONTROL_ERROR_CODES.CANCEL_ACK_MISSING,
    CANCEL_DUPLICATE: NATIVE_TASK_CONTROL_ERROR_CODES.CANCEL_DUPLICATE,
    TERMINAL_BARRIER: NATIVE_TASK_CONTROL_ERROR_CODES.TERMINAL_BARRIER,
    TERMINAL_REPLAY_CONFLICT: NATIVE_TASK_CONTROL_ERROR_CODES.TERMINAL_REPLAY_CONFLICT,
    SUCCESSION_OVERLAP: NATIVE_TASK_CONTROL_ERROR_CODES.SUCCESSION_OVERLAP,
    SUCCESSION_AMBIGUOUS: NATIVE_TASK_CONTROL_ERROR_CODES.SUCCESSION_AMBIGUOUS,
    WAIT_DUPLICATE: NATIVE_TASK_CONTROL_ERROR_CODES.WAIT_DUPLICATE,
    LATE_EVENT: NATIVE_TASK_CONTROL_ERROR_CODES.LATE_EVENT,
    UNDECLARED_ROLE: NATIVE_TASK_CONTROL_ERROR_CODES.UNDECLARED_ROLE,
    REPLACEMENT_EXHAUSTED: NATIVE_TASK_CONTROL_ERROR_CODES.REPLACEMENT_EXHAUSTED,
    SURFACE_UNAVAILABLE: NATIVE_TASK_CONTROL_ERROR_CODES.SURFACE_UNAVAILABLE,
    FORGE_DEFUNCT: NATIVE_TASK_CONTROL_ERROR_CODES.FORGE_DEFUNCT,
} as const);

export type NativeTaskControlErrorCode =
    typeof NATIVE_TASK_CONTROL_ERROR_CODES[keyof typeof NATIVE_TASK_CONTROL_ERROR_CODES];

export type NativeTaskControlStableErrorCode =
    typeof NATIVE_TASK_CONTROL_STABLE_ERROR_CODES[keyof typeof NATIVE_TASK_CONTROL_STABLE_ERROR_CODES];

export class NativeTaskControlError extends Error {
    readonly code: NativeTaskControlErrorCode;
    readonly details: Readonly<Record<string, unknown>>;

    constructor(
        code: NativeTaskControlErrorCode,
        details: Readonly<Record<string, unknown>> = {},
    ) {
        super(code);
        this.name = 'NativeTaskControlError';
        this.code = code;
        this.details = Object.freeze({ ...details });
    }
}

export function failNativeTaskControl(
    code: NativeTaskControlErrorCode,
    details?: Readonly<Record<string, unknown>>,
): never {
    throw new NativeTaskControlError(code, details);
}
