---
title: "51b4bd866bf4520e.js"
path: "C:/Users/Craig/Corvus/Astrologer/astrologer-desktop/out/_next/static/chunks/51b4bd866bf4520e.js"
loc: 32
complexity: 1698
logic_score: 1.00
style_score: 1.00
intel_score: 9.40
overall_score: 3.80
---

## Intent
A functional component of the Corvus Star static analysis matrix.

## Gungnir Matrix Breakdown
- **Logic [L]**: 1.0/10
- **Style [S]**: 1.0/10
- **Intel [I]**: 9.4/10
- **Gravity [G]**: 0 interactions (Agent Activity Hotspot)

## Neural Pathways

### Imports
Minimal internal dependencies.

### Exports
- `eu`
- `es`
- `o`
- `u`
- `s`
- `d`
- `n`
- `a`
- `o`
- `m`
- `f`
- `v`
- `g`
- `h`
- `$`
- `b`
- `y`
- `_`
- `x`
- `k`
- `w`
- `I`
- `S`
- `z`
- `U`
- `O`
- `D`
- `j`
- `N`
- `P`
- `E`
- `T`
- `A`
- `C`
- `R`
- `F`
- `M`
- `W`
- `V`
- `K`
- `X`
- `q`
- `Y`
- `H`
- `et`
- `ei`
- `en`
- `er`
- `ea`
- `eo`
- `eu`
- `es`
- `el`
- `ed`
- `ec`
- `em`
- `ef`
- `ep`
- `ev`
- `eg`
- `eh`
- `e$`
- `eb`
- `ey`
- `e_`
- `ex`
- `ek`
- `ez`
- `eZ`
- `eU`
- `eO`
- `eD`
- `to`
- `th`
- `t$`
- `tb`
- `tU`
- `tO`
- `t3`
- `it`
- `iZ`
- `iO`
- `iN`
- `iX`
- `iY`
- `iH`
- `iQ`
- `i6`
- `i2`
- `i7`
- `ne`
- `nn`
- `na`
- `nd`
- `nv`
- `n$`
- `nk`
- `nI`
- `nS`
- `nZ`
- `nP`
- `nE`
- `nT`
- `nA`
- `nC`
- `nL`
- `nJ`
- `nF`
- `nM`
- `nG`
- `nV`
- `nX`
- `nq`
- `nY`
- `nH`
- `nQ`
- `n0`
- `n4`
- `n6`
- `n1`
- `n2`
- `n9`
- `n5`
- `n3`
- `n7`
- `n8`
- `re`
- `rt`
- `ri`
- `rn`
- `rr`
- `ra`
- `ro`
- `ru`
- `rs`
- `rl`
- `rc`
- `rm`
- `rf`
- `rp`
- `rv`
- `rg`
- `rh`
- `r$`
- `rb`
- `ry`
- `r_`
- `rx`
- `rk`
- `rw`
- `rI`
- `rS`
- `rz`
- `rZ`
- `rU`
- `rO`
- `rD`
- `rj`
- `rN`
- `rP`
- `rE`
- `rT`
- `rA`
- `rC`
- `rL`
- `rR`
- `rJ`
- `rF`
- `rM`
- `rW`
- `rB`
- `rG`
- `rV`
- `rK`
- `rX`
- `rq`
- `rY`
- `rH`
- `rQ`
- `r0`
- `r4`
- `r6`
- `r1`
- `r2`
- `r9`
- `r5`
- `r3`
- `r7`
- `r8`
- `ae`
- `at`
- `ai`
- `an`
- `ar`
- `aa`
- `ao`
- `au`
- `as`
- `al`
- `ad`
- `ac`
- `am`
- `af`
- `ap`
- `av`
- `ag`
- `ah`
- `a$`
- `ab`
- `ay`
- `a_`
- `ax`
- `ak`
- `aw`
- `aI`
- `aS`
- `az`
- `aZ`
- `aU`
- `aO`
- `aD`
- `aj`
- `aN`
- `aP`
- `aE`
- `aT`
- `aA`
- `aC`
- `aL`
- `ob`
- `oy`
- `ow`
- `oS`
- `oZ`
- `oO`
- `oX`
- `oH`
- `o0`
- `o6`
- `o1`
- `o2`
- `o9`
- `o3`
- `o7`
- `ue`
- `ui`
- `ur`
- `uo`
- `us`
- `ud`
- `um`
- `up`
- `ug`
- `u$`
- `uy`
- `ux`
- `uw`
- `uS`
- `uZ`
- `uO`
- `uj`
- `uN`
- `uP`
- `uE`
- `uA`
- `uL`
- `uR`
- `uJ`
- `uF`
- `uM`
- `uB`
- `uV`
- `uX`
- `uq`
- `uH`
- `u0`
- `u6`
- `u2`
- `u5`
- `u7`
- `se`
- `si`
- `sr`
- `sa`
- `su`
- `ss`
- `sl`
- `sc`
- `sf`
- `sv`
- `sh`
- `sb`
- `s_`
- `sx`
- `sk`
- `sI`
- `sz`
- `sU`
- `sO`
- `sj`
- `sP`
- `sT`
- `sC`
- `sR`
- `sF`
- `sM`
- `sB`
- `sV`
- `sX`
- `sY`
- `sQ`
- `s4`
- `s1`
- `s9`
- `s3`
- `s8`
- `lt`
- `ln`
- `la`
- `lu`
- `ls`
- `ll`
- `ld`
- `lf`
- `lv`
- `lg`
- `l$`
- `lb`
- `lw`
- `lI`
- `lS`
- `lz`
- `lZ`
- `lU`
- `t`
- `lM`
- `lW`
