---
title: "cc759f7c2413b7ff.js"
path: "C:/Users/Craig/Corvus/Astrologer/astrologer-desktop/out/_next/static/chunks/cc759f7c2413b7ff.js"
loc: 1
complexity: 2791
logic_score: 1.00
style_score: 1.00
intel_score: 9.40
overall_score: 3.80
---

## Intent
A functional component of the Corvus Star static analysis matrix.

## Gungnir Matrix Breakdown
- **Logic [L]**: 1.0/10
- **Style [S]**: 1.0/10
- **Intel [I]**: 9.4/10
- **Gravity [G]**: 0 interactions (Agent Activity Hotspot)

## Neural Pathways

### Imports
Minimal internal dependencies.

### Exports
- `l`
- `a`
- `o`
- `a`
- `a`
- `o`
- `o`
- `i`
- `c`
- `r`
- `l`
- `a`
- `o`
- `E`
- `x`
- `T`
- `O`
- `R`
- `u`
- `s`
- `c`
- `f`
- `d`
- `p`
- `m`
- `h`
- `g`
- `b`
- `w`
- `k`
- `S`
- `E`
- `H`
- `Y`
- `J`
- `Z`
- `el`
- `ea`
- `eo`
- `ei`
- `eu`
- `ec`
- `ef`
- `eL`
- `eR`
- `eM`
- `eI`
- `eD`
- `eF`
- `eA`
- `ej`
- `eU`
- `eB`
- `eV`
- `eH`
- `e$`
- `e0`
- `e1`
- `e2`
- `e3`
- `e4`
- `e5`
- `e9`
- `e7`
- `tl`
- `ta`
- `to`
- `ti`
- `tu`
- `ts`
- `tc`
- `tf`
- `td`
- `tm`
- `th`
- `tg`
- `tv`
- `ty`
- `tb`
- `tw`
- `tk`
- `tE`
- `tx`
- `t_`
- `tC`
- `tT`
- `tz`
- `tM`
- `tD`
- `tF`
- `t$`
- `tQ`
- `tW`
- `tq`
- `tK`
- `t`
- `nl`
- `na`
- `ny`
- `nb`
- `nS`
- `nE`
- `nP`
- `nN`
- `nC`
- `nL`
- `nR`
- `nM`
- `nI`
- `nD`
- `nF`
- `nj`
- `nU`
- `nB`
- `nV`
- `nH`
- `nX`
- `nG`
- `n0`
- `re`
- `rn`
- `rr`
- `rl`
- `rs`
- `rc`
- `rf`
- `rd`
- `rp`
- `rm`
- `rg`
- `rv`
- `ry`
- `rb`
- `rw`
- `rk`
- `rS`
- `rE`
- `rx`
- `r_`
- `rN`
- `rF`
- `rA`
- `rj`
- `rU`
- `rB`
- `rK`
- `rX`
- `rG`
- `rY`
- `rJ`
- `rZ`
- `r0`
- `r4`
- `r5`
- `r6`
- `r8`
- `r9`
- `r7`
- `le`
- `lt`
- `ln`
- `lr`
- `lu`
- `ls`
- `lc`
- `lg`
- `lb`
- `lw`
- `lk`
- `lP`
- `lN`
- `lC`
- `lO`
- `lz`
- `lM`
- `lI`
- `lD`
- `lF`
- `t`
- `n`
- `r`
- `l`
- `a`
- `o`
- `i`
- `s`
- `c`
- `f`
- `d`
- `p`
- `m`
- `lB`
- `lV`
- `lH`
- `l$`
- `lQ`
- `lW`
- `lK`
- `lX`
- `lG`
- `lY`
- `l0`
- `l1`
- `l2`
- `l5`
- `l6`
- `l8`
- `l9`
- `l7`
- `at`
- `an`
- `ar`
- `ah`
- `ag`
- `av`
- `ay`
- `ab`
- `aw`
- `ak`
- `aS`
- `aE`
- `ax`
- `a_`
- `aP`
- `aN`
- `aC`
- `aT`
- `aO`
- `az`
- `aL`
- `aR`
- `aM`
- `aI`
- `aD`
- `aF`
- `aA`
- `aj`
- `aU`
- `aB`
- `aV`
- `aH`
- `a$`
- `aQ`
- `aW`
- `aq`
- `aK`
- `aX`
- `aG`
- `aY`
- `aJ`
- `aZ`
- `a0`
- `a1`
- `a2`
- `a3`
- `a4`
- `a5`
- `a6`
- `a8`
- `a9`
- `a7`
- `oe`
- `ot`
- `on`
- `or`
- `ol`
- `oa`
- `oo`
- `oi`
- `ou`
- `os`
- `oc`
- `of`
- `od`
- `op`
- `om`
- `oh`
- `og`
- `ov`
- `oy`
- `ob`
- `ow`
- `ok`
- `oP`
- `oC`
- `oT`
- `oO`
- `oz`
- `oL`
- `oR`
- `oM`
- `oI`
- `oD`
- `oF`
- `oA`
- `oB`
- `oV`
- `oH`
- `o$`
- `oQ`
- `oW`
- `oq`
- `oK`
- `oX`
- `oG`
- `oY`
- `oJ`
- `oZ`
- `o0`
- `o2`
- `o3`
- `o4`
- `o5`
- `o6`
- `o8`
- `o9`
- `o7`
- `ie`
- `it`
- `ir`
- `il`
- `ia`
- `io`
- `ii`
- `iu`
- `is`
- `ic`
- `id`
- `ip`
- `im`
- `ih`
- `ig`
- `iv`
- `iy`
- `ib`
- `iw`
- `ik`
- `iS`
- `iE`
- `ix`
- `i_`
- `iP`
- `iN`
- `iC`
- `iT`
- `iL`
- `iM`
- `iD`
- `iF`
- `iA`
- `ij`
- `iU`
- `iB`
- `iV`
- `iH`
- `i$`
- `i1`
- `i2`
- `i3`
- `i6`
- `i8`
- `i9`
- `i7`
- `ue`
- `ut`
- `ur`
- `ul`
- `ua`
- `uo`
- `ui`
- `uu`
- `us`
- `uc`
- `uf`
- `ud`
- `um`
- `uh`
- `ug`
- `uv`
- `uy`
- `ub`
- `u4`
- `u5`
- `u6`
- `u8`
- `u9`
- `u7`
- `se`
- `st`
- `sn`
- `sr`
- `sl`
- `sa`
- `so`
- `si`
- `su`
- `ss`
- `sc`
- `sf`
- `sd`
- `sp`
- `sm`
- `sh`
- `sg`
- `sv`
- `sy`
- `sb`
- `sw`
- `sk`
- `sS`
- `sE`
- `sx`
- `s_`
- `sP`
- `sN`
- `sC`
- `sT`
- `sO`
- `sF`
- `sA`
- `sj`
- `sU`
- `sB`
- `sV`
- `sH`
- `s$`
- `sQ`
- `sW`
- `sY`
- `sJ`
- `sZ`
- `s1`
- `s2`
- `s3`
- `s4`
- `s5`
- `s6`
- `s8`
- `ce`
- `ct`
- `cn`
- `cr`
- `cl`
- `ca`
- `cu`
- `cs`
- `cc`
- `cf`
- `cv`
- `cy`
- `cb`
- `cw`
- `ck`
- `cS`
- `cE`
- `cx`
- `c_`
- `cP`
- `cN`
- `cC`
- `cT`
- `cO`
- `cz`
- `cL`
- `cR`
- `cM`
- `l`
- `cI`
- `cD`
- `cF`
- `cA`
- `cj`
- `cU`
- `cB`
- `cV`
- `cH`
- `c$`
- `cQ`
- `cq`
- `cK`
- `cX`
- `cG`
- `cZ`
- `c2`
- `c3`
- `c4`
- `c5`
- `c6`
- `c8`
- `c9`
- `c7`
- `fe`
- `ft`
- `fn`
- `fl`
- `fa`
- `fo`
- `fi`
- `fu`
- `fs`
- `ff`
- `fd`
- `fp`
- `fh`
- `fg`
- `fy`
- `fb`
- `fw`
- `fk`
- `fS`
- `fE`
- `fx`
- `fP`
- `fN`
- `fC`
- `fT`
- `fz`
- `fL`
- `fB`
- `fV`
- `fH`
- `f$`
- `fQ`
- `fW`
- `fq`
- `fX`
- `fG`
- `t`
- `fY`
- `e`
- `t`
- `n`
- `fJ`
- `fZ`
- `d`
- `p`
- `o`
- `a`
- `i`
- `s`
- `T`
- `O`
- `z`
- `L`
- `e`
- `e`
- `R`
- `D`
- `i`
- `T`
- `M`
- `D`
- `A`
