---
title: "quarto-search.js"
path: "C:/Users/Craig/Corvus/CorvusStar/docs/site_libs/quarto-search/quarto-search.js"
loc: 1078
complexity: 102
logic_score: 0.50
style_score: 1.00
intel_score: 5.04
overall_score: 1.85
---

## Intent
A functional component of the Corvus Star static analysis matrix.

## Interaction Protocol
Import and utilize via the standard project structure.

## Gungnir Matrix Breakdown
- **Logic [L]**: 0.5/10
- **Style [S]**: 1.0/10
- **Intel [I]**: 5.0/10
- **Gravity [G]**: 131 interactions (Agent Activity Hotspot)



## Neural Pathways

### Imports
Minimal internal dependencies.

### Exports
- `kQueryArg`
- `kResultsArg`
- `kItemTypeMoreHref`
- `searchEl`
- `window`
- `quartoSearchOptions`
- `language`
- `searchOptionEl`
- `jsonStr`
- `currentUrl`
- `query`
- `showSearchResults`
- `mainEl`
- `replacementUrl`
- `highlighting`
- `resetHighlighting`
- `resetFn`
- `detachedMediaQuery`
- `plugins`
- `lastState`
- `autocomplete`
- `items`
- `groupedItems`
- `hrefParts`
- `baseHref`
- `isDocumentItem`
- `items`
- `reshapedItems`
- `count`
- `firstItem`
- `collapseMatches`
- `collapseCount`
- `target`
- `isExpanded`
- `remainingCount`
- `i`
- `windowReference`
- `limit`
- `fuseSearchOptions`
- `hasQuery`
- `count`
- `libDir`
- `logo`
- `event`
- `kbds`
- `focusedEl`
- `isFormElFocused`
- `inputEl`
- `throttle`
- `waiting`
- `configurePlugins`
- `autocompletePlugins`
- `algoliaOptions`
- `apiKey`
- `appId`
- `algoliaInsightsDeferredPlugin`
- `window`
- `algoliaInsightsPlugin`
- `events`
- `chunkSize`
- `itemChunks`
- `eventItems`
- `i`
- `events`
- `deferredLoadPlugin`
- `plugin`
- `subscribeObj`
- `wrappedPlugin`
- `plugin`
- `plugin`
- `plugin`
- `plugin`
- `plugin`
- `validateItems`
- `item`
- `missingFields`
- `missingFieldList`
- `lastQuery`
- `showCopyLink`
- `language`
- `inputSuffixEl`
- `copyButtonEl`
- `linkIcon`
- `checkIcon`
- `shareIconEl`
- `clipboard`
- `copyUrl`
- `button`
- `icon`
- `fuseIndex`
- `shownWarning`
- `kFuseIndexOptions`
- `readSearchData`
- `fuse`
- `response`
- `inputElement`
- `focusSearchInput`
- `inputEl`
- `kItemTypeDoc`
- `kItemTypeMore`
- `kItemTypeItem`
- `kItemTypeError`
- `renderItem`
- `createDocumentCard`
- `iconEl`
- `titleEl`
- `titleContents`
- `showParent`
- `crumbsOut`
- `crumbClz`
- `crumbEl`
- `titleContainerEl`
- `textEls`
- `sectionEl`
- `descEl`
- `textContainerEl`
- `containerEl`
- `linkEl`
- `classes`
- `createMoreCard`
- `moreCardEl`
- `toggleExpanded`
- `expanded`
- `createSectionCard`
- `sectionEl`
- `createSection`
- `descEl`
- `titleEl`
- `linkEl`
- `createErrorCard`
- `descEl`
- `titleEl`
- `errorEl`
- `positionPanel`
- `panelEl`
- `inputEl`
- `highlightMatch`
- `start`
- `startMark`
- `endMark`
- `end`
- `startInfo`
- `endInfo`
- `clipStart`
- `clipStart`
- `spacePos`
- `clipEnd`
- `clipEnd`
- `spacePos`
- `findSpace`
- `stepPos`
- `char`
- `clearHighlight`
- `childNodes`
- `i`
- `node`
- `escapeRegExp`
- `highlight`
- `termRegex`
- `childNodes`
- `i`
- `node`
- `text`
- `startIndex`
- `matchIndex`
- `markFragment`
- `prefix`
- `mark`
- `offsetURL`
- `offset`
- `getMeta`
- `metas`
- `i`
- `algoliaSearch`
- `window`
- `applicationId`
- `searchOnlyApiKey`
- `indexName`
- `indexFields`
- `searchClient`
- `searchParams`
- `searchAnalytics`
- `remappedHits`
- `newItem`
- `mappedName`
- `subSearchTerm`
- `subSearchFuse`
- `kFuseMaxWait`
- `fuseSearch`
- `index`
- `then`
- `resultsRaw`
- `now`
- `results`
- `addParam`
- `anchorParts`
- `baseUrl`
- `sep`
