---
title: "quarto-nav.js"
path: "C:\Users\Craig\Corvus\CorvusStar\docs\site_libs\quarto-nav\quarto-nav.js"
loc: 273
complexity: 36
logic_score: 0.50
style_score: 4.05
intel_score: 4.77
overall_score: 1.27
---

## Intent
The `quarto-nav.js` sector implements high-complexity logic focusing on headroomChanged, announceDismiss, annEl, annId, announceRegister, annEl, annId, isDismissed, actionEl, init, lastScrollTop, scrollDownBuffer, scrollUpBuffer, btn, hideBackToTop, showBackToTop, currentScrollTop, throttle, timeout, context, args, later, headerOffset, headerEl, footerOffset, footerEl, dashboardOffset, dashboardNavEl, updateDocumentOffsetWithoutAnimation, updateDocumentOffset, topOffset, bodyOffset, bodyEl, sidebars, mainContainer, linkStyle, header, headroom, sidebars, sidebars, frozen, headerEl, observer, links, i, sharingLinks, i, sharingLink, href, navSidebar, activeItem, resizeObserver, elBottom, viewBottom. It forms a critical node in the Gungnir Matrix.

## Interaction Protocol
Integrate via headroomChanged, announceDismiss, annEl, annId, announceRegister, annEl, annId, isDismissed, actionEl, init, lastScrollTop, scrollDownBuffer, scrollUpBuffer, btn, hideBackToTop, showBackToTop, currentScrollTop, throttle, timeout, context, args, later, headerOffset, headerEl, footerOffset, footerEl, dashboardOffset, dashboardNavEl, updateDocumentOffsetWithoutAnimation, updateDocumentOffset, topOffset, bodyOffset, bodyEl, sidebars, mainContainer, linkStyle, header, headroom, sidebars, sidebars, frozen, headerEl, observer, links, i, sharingLinks, i, sharingLink, href, navSidebar, activeItem, resizeObserver, elBottom, viewBottom. Follow the Linscott Standard for this sector.

## Gungnir Matrix Breakdown
- **Logic [L]**: 0.5/10
- **Style [S]**: 4.0/10
- **Intel [I]**: 4.8/10
- **Gravity [G]**: 35 interactions (Agent Activity Hotspot)



## Neural Pathways

### Imports
Minimal internal dependencies.

### Exports
- `headroomChanged`
- `announceDismiss`
- `annEl`
- `annId`
- `announceRegister`
- `annEl`
- `annId`
- `isDismissed`
- `actionEl`
- `init`
- `lastScrollTop`
- `scrollDownBuffer`
- `scrollUpBuffer`
- `btn`
- `hideBackToTop`
- `showBackToTop`
- `currentScrollTop`
- `throttle`
- `timeout`
- `context`
- `args`
- `later`
- `headerOffset`
- `headerEl`
- `footerOffset`
- `footerEl`
- `dashboardOffset`
- `dashboardNavEl`
- `updateDocumentOffsetWithoutAnimation`
- `updateDocumentOffset`
- `topOffset`
- `bodyOffset`
- `bodyEl`
- `sidebars`
- `mainContainer`
- `linkStyle`
- `header`
- `headroom`
- `sidebars`
- `sidebars`
- `frozen`
- `headerEl`
- `observer`
- `links`
- `i`
- `sharingLinks`
- `i`
- `sharingLink`
- `href`
- `navSidebar`
- `activeItem`
- `resizeObserver`
- `elBottom`
- `viewBottom`
