#!/usr/bin/env python3
"""
[ALFRED] The Danger Room
Identity: ALFRED
Purpose: Automated Test Scaffolding & Safety Net Generation.

Reads the .agent/tech_debt_ledger.json
Targets high-risk files and uses the Antigravity Bridge to scaffold a rigorous test suite.
Mandates human-in-the-loop (diff review) before committing tests to the manor.
"""

import argparse
import asyncio
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any, Optional

# Ensure UTF-8 output for box-drawing characters
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding='utf-8')

project_root = Path(__file__).parent.parent.parent.absolute()
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from src.core.sovereign_hud import SovereignHUD
from src.cstar.core.uplink import query_bridge

# Configure Logging
logging.basicConfig(
    filename=str(project_root / "sovereign_activity.log"),
    level=logging.INFO,
    format="[%(asctime)s] [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S"
)

class DangerRoom:
    """Automated Scaffolding with Human Oversight."""

    def __init__(self, target_limit: int = 1, max_retries: int = 3, token_limit_per_session: int = 50000):
        self.ledger_path = project_root / ".agent" / "tech_debt_ledger.json"
        self.target_limit = target_limit
        self.max_retries = max_retries
        self.token_limit = token_limit_per_session # Heuristic for now
        
        # Enforce ALFRED persona
        SovereignHUD.PERSONA = "ALFRED"

    def _read_ledger(self) -> list[dict[str, Any]]:
        """Reads the tech debt ledger generated by Archive Consolidator."""
        if not self.ledger_path.exists():
            SovereignHUD.persona_log("WARN", "No tech debt ledger found. Run `archive_consolidator.py` first.")
            return []
            
        try:
            data = json.loads(self.ledger_path.read_text(encoding="utf-8"))
            targets = data.get("top_targets", [])
            # Filter for files that specifically lack coverage
            return [t for t in targets if not t.get("coverage")]
        except json.JSONDecodeError:
            SovereignHUD.persona_log("ERROR", "Tech debt ledger is corrupted.")
            return []

    async def _scaffold_test(self, file_path_str: str) -> Optional[str]:
        """Queries the bridge to generate a test suite."""
        full_path = project_root / file_path_str
        if not full_path.exists():
            return None
            
        code_content = full_path.read_text(encoding="utf-8")
        
        prompt = f"""
[CRITICAL INSTRUCTION]
You are ALFRED, the stringent testing framework for the Corvus Star Manor.
Your task is to generate a comprehensive `pytest` suite for the following target file.

TARGET FILE ({file_path_str}):
```python
{code_content}
```

[MANDATORY SECURITY CONSTRAINTS]
1. DO NOT write "tautological tests" (shallow mocking that only asserts a mock was called).
2. You MUST verify the actual mathematical or logical state changes of the functions.
3. If dependencies must be mocked, ensure the return values are structurally realistic.
4. Output ONLY the raw Python code for the test file. No markdown formatting, no explanations. 
5. Start the file strictly with standard imports (pytest, etc).

Generate the robust test suite now.
"""
        context = {
            "persona": "ALFRED",
            "target_interface": file_path_str
        }
        
        SovereignHUD.persona_log("INFO", f"Bridging to Forge for {Path(file_path_str).name}...")
        
        for attempt in range(self.max_retries):
            try:
                response = await query_bridge(prompt, context)
                if response and response.get("status") == "success":
                    # The bridge can sometimes wrap the code in JSON even for ALFRED if we didn't ask it to.
                    # Or it might return raw text based on our prompt.
                    data = response.get("data", {})
                    
                    # Handle varying bridge return structures
                    if isinstance(data, dict):
                         if "code" in data:
                             return data["code"]
                         elif "raw" in data:
                             code = data["raw"]
                         else:
                             # It might have successfully formatted JSON if the bridge mapped ALFRED
                             return json.dumps(data)
                    else:
                        code = str(data)
                        
                    # Standard sanitize block
                    return self._clean_markdown(code)
                    
            except Exception as e:
                SovereignHUD.persona_log("WARN", f"Forge attempt {attempt+1} failed: {e}")
                await asyncio.sleep(2)
                
        SovereignHUD.persona_log("ERROR", "Max retries exceeded for scaffolding.")
        return None

    def _clean_markdown(self, text: str) -> str:
        """Strips markdown code blocks."""
        text = text.strip()
        if text.startswith("```python"):
            text = text[9:]
        elif text.startswith("```"):
            text = text[3:]
        if text.endswith("```"):
            text = text[:-3]
        return text.strip() + "\n"

    def _human_review(self, target_file: str, test_code: str) -> bool:
        """Presents the generated test to the user for diff review."""
        SovereignHUD.box_separator()
        SovereignHUD.box_row("HUMAN IN THE LOOP", "REVIEW REQUIRED", SovereignHUD.YELLOW)
        SovereignHUD.box_row("TARGET", target_file, SovereignHUD.CYAN)
        SovereignHUD.box_separator()
        
        lines = test_code.splitlines()
        preview_lines = lines[:15]
        for line in preview_lines:
             SovereignHUD.box_row("  ", line, SovereignHUD.GREEN, dim_label=True)
             
        if len(lines) > 15:
             SovereignHUD.box_row("  ", f"... (+ {len(lines)-15} more lines)", SovereignHUD.GREEN, dim_label=True)
             
        SovereignHUD.box_separator()
        try:
             # Basic prompt. In a real TUI, this would use Textual.
             ans = input(f"{SovereignHUD.get_theme()['main']}[ALFRED] Sir, I have generated a framework. Shall I commit this to the test matrix? (y/N): {SovereignHUD.RESET}")
             return ans.strip().lower() in ['y', 'yes']
        except (KeyboardInterrupt, EOFError):
             return False

    def _commit_test(self, target_file: str, test_code: str) -> bool:
        """Writes the approved test to the tests directory."""
        target_path = Path(target_file)
        # Attempt to map it to a logical test position. 
        # By default, empire_tests serves as our integration/generated holding pen.
        test_dir = project_root / "tests" / "empire_tests"
        test_dir.mkdir(parents=True, exist_ok=True)
        
        test_name = f"test_{target_path.name}"
        test_path = test_dir / test_name
        
        try:
             test_path.write_text(test_code, encoding="utf-8")
             SovereignHUD.persona_log("SUCCESS", f"Committed: {test_path.relative_to(project_root)}")
             return True
        except Exception as e:
             SovereignHUD.persona_log("ERROR", f"Failed to commit {test_name}: {e}")
             return False

    async def execute(self):
        """Main execution sequence."""
        SovereignHUD.box_top("[A] THE DANGER ROOM")
        SovereignHUD.box_row("DIRECTIVE", "TEST SCAFFOLDING & VERIFICATION", SovereignHUD.CYAN)
        
        targets = self._read_ledger()
        if not targets:
            SovereignHUD.box_row("STATUS", "No viable targets identified in ledger.", SovereignHUD.GREEN)
            SovereignHUD.box_bottom()
            return
            
        selected_targets = targets[:self.target_limit]
        SovereignHUD.box_row("ISOLATED TARGETS", str(len(selected_targets)), SovereignHUD.YELLOW)
        
        for t in selected_targets:
            file_str = t['file']
            SovereignHUD.box_separator()
            SovereignHUD.box_row("ENGAGING", Path(file_str).name, SovereignHUD.MAGENTA)
            
            test_code = await self._scaffold_test(file_str)
            
            if not test_code:
                SovereignHUD.box_row("RESULT", "Scaffolding Failed.", SovereignHUD.RED)
                continue
                
            approved = self._human_review(file_str, test_code)
            
            if approved:
                self._commit_test(file_str, test_code)
            else:
                SovereignHUD.persona_log("INFO", "Scaffolding rejected by user. Discarding trace.")
                
        SovereignHUD.box_bottom()

def main():
    parser = argparse.ArgumentParser(description="The Danger Room - Test Scaffolding")
    parser.add_argument("--limit", type=int, default=1, help="Number of files to process per session")
    args = parser.parse_args()

    room = DangerRoom(target_limit=args.limit)
    try:
        asyncio.run(room.execute())
        return 0
    except KeyboardInterrupt:
        SovereignHUD.persona_log("WARN", "Danger Room protocol aborted.")
        return 1
    except Exception as e:
        SovereignHUD.persona_log("ERROR", f"Danger Room protocol failed: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
